# PostgreSQL Database Configuration for CohortBridge
# Suitable for large-scale deployments with database integration

database:
  type: postgres
  host: localhost
  port: 5432
  user: cohort_user
  password: secure_password_here
  dbname: patient_records
  table: patients
  fields:
    - name:first_name         # First name with normalization
    - name:last_name          # Last name with normalization
    - date:birth_date         # Date of birth with normalization
    - zip:postal_code         # ZIP code with normalization
    - gender:gender           # Gender with normalization
  is_tokenized: false

# Network configuration
peer:
  host: 192.168.1.50
  port: 8443

listen_port: 8443

# Security configuration
security:
  rate_limit_per_min: 10  # Higher rate limit for database operations

# Timeout configuration
timeouts:
  connection_timeout: 45s
  read_timeout: 180s      # Longer timeouts for database queries
  write_timeout: 180s
  idle_timeout: 600s
  handshake_timeout: 45s

# Logging configuration
logging:
  level: "info"
  file: "logs/postgres_cohort_bridge.log"
  max_size: 200           # Larger log files for database operations
  max_backups: 5
  max_age: 60
  enable_audit: true
  audit_file: "logs/postgres_audit.log"

# Matching parameters
matching:
  hamming_threshold: 20
  jaccard_threshold: 0.7

# Note: PostgreSQL integration provides scalable solutions for large datasets
# with built-in transaction support and data integrity guarantees 
