# Example configuration file for HIPAA-compliant fuzzy matching system
# Copy this file to config.yaml and modify the values as needed

database:
  type: csv
  filename: data/patients.csv  # Path to your patient data CSV file
  fields:
    - first_name              # Patient first name column  
    - last_name               # Patient last name column
    - dob                     # Date of birth column (YYYY-MM-DD format)
    - zip                     # ZIP code column
  # Optional: Add normalization to fields for improved matching accuracy
  # Use format: method:field_name
  # Supported methods: name, date, gender, zip
  # Examples:
  #   - name:first_name       # Apply name normalization (lowercase, remove punctuation, normalize spaces)
  #   - name:last_name        # Apply name normalization
  #   - date:dob              # Apply date normalization (standardize to YYYY-MM-DD)
  #   - zip:zip               # Apply ZIP normalization (extract first 5 digits)

# Network configuration for peer-to-peer matching
peer:
  host: 127.0.0.1   # IP address of the peer to connect to
  port: 8081        # Port number of the peer

listen_port: 8082   # Port to listen on for incoming connections

# Security configuration
security:
  rate_limit_per_min: 5  # Maximum connections per minute per IP

# Timeout configuration
timeouts:
  connection_timeout: 30s
  read_timeout: 60s
  write_timeout: 60s
  idle_timeout: 300s
  handshake_timeout: 30s

# Logging configuration
logging:
  level: "info"
  file: "logs/cohort-bridge.log"
  max_size: 100
  max_backups: 3
  max_age: 30

# Matching parameters
matching:
  hamming_threshold: 20      # Maximum Hamming distance for matches
  jaccard_threshold: 0.7     # Minimum Jaccard similarity for matches

# Note: All protocols use secure matching by default for maximum privacy protection 