# Secure configuration for maximum privacy and security
# Suitable for production deployments with sensitive data

database:
  type: csv
  filename: data/patients.csv
  fields:
    - name:first_name         # First name with normalization
    - name:last_name          # Last name with normalization  
    - date:date_of_birth      # Date of birth with normalization
    - zip:zip_code            # ZIP code with normalization
    - gender:gender           # Gender with normalization
  is_tokenized: false
  # Encryption will be inferred from presence of encryption_key or encryption_key_file
  encryption_key_file: "data/encryption.key"

# Network configuration
peer:
  host: 192.168.1.100
  port: 8443

listen_port: 8443

# Security configuration
security:
  rate_limit_per_min: 3  # Conservative rate limiting

# Timeout configuration
timeouts:
  connection_timeout: 60s
  read_timeout: 120s
  write_timeout: 120s
  idle_timeout: 600s
  handshake_timeout: 60s

# Comprehensive logging for audit compliance
logging:
  level: "info"
  file: "logs/secure_cohort_bridge.log"
  max_size: 50
  max_backups: 10
  max_age: 90
  enable_syslog: true
  enable_audit: true
  audit_file: "logs/security_audit.log"

# Conservative matching thresholds for high precision
matching:
  hamming_threshold: 15      # Stricter threshold
  jaccard_threshold: 0.8     # Higher similarity requirement

# Note: All protocols use secure zero-knowledge matching by default
