database:
  type: csv
  filename: data/patients_short.csv
  fields:
    - first_name
    - last_name
    - dob
    - zip
peer:
  host: 127.0.0.1
  port: 9002
listen_port: 9000
private_key: 240c1878d85eebe9d8a80cb7fadda30c854a7a72797c441bd1c547b10ac754b5
