database:
  type: csv
  filename: data/patients_a.csv
  fields:
    - FIRST
    - LAST
    - BIRTHDATE
    - ZIP
peer:
  host: 127.0.0.1
  port: 8082
listen_port: 8081
private_key: 240c1878d85eebe9d8a80cb7fadda30c854a7a72797c441bd1c547b10ac754b5
