database:
  type: postgres
  host: localhost
  port: 5432
  user: dbuser
  password: dbpass
  dbname: ehr
  table: patients
  fields:
    - first_name
    - last_name
    - dob
    - zip
peer:
  host: 127.0.0.1
  port: 9001
listen_port: 9000
private_key: 240c1878d85eebe9d8a80cb7fadda30c854a7a72797c441bd1c547b10ac754b5
