# Example configuration with normalization for cohort-bridge
# Copy this file to config.yaml and modify the values as needed

database:
  type: csv
  filename: data/patients.csv  # Path to your patient data CSV file
  fields:
    - name:FIRST              # Patient first name column with name normalization
    - name:LAST               # Patient last name column with name normalization
    - date:DATE_OF_BIRTH      # Date of birth column with date normalization
    - zip:ZIP                 # ZIP code column with ZIP normalization
    - gender:GENDER           # Gender column with gender normalization

# Network configuration for peer-to-peer matching
peer:
  host: 127.0.0.1   # IP address of the peer to connect to
  port: 8081        # Port number of the peer

listen_port: 8082   # Port to listen on for incoming connections

# Security configuration
security:
  allowed_ips:
    - "127.0.0.1"
    - "::1"
  require_ip_check: true
  max_connections: 10
  rate_limit_per_min: 5

# Timeout configuration
timeouts:
  connection_timeout: 30s
  read_timeout: 60s
  write_timeout: 60s
  idle_timeout: 300s
  handshake_timeout: 30s

# Logging configuration
logging:
  level: "info"
  file: "logs/cohort-bridge.log"
  max_size: 100
  max_backups: 3
  max_age: 30
  enable_audit: true
  audit_file: "logs/audit.log"

# Matching parameters
matching:
  hamming_threshold: 20      # Maximum Hamming distance for matches
  jaccard_threshold: 0.7     # Minimum Jaccard similarity for matches

# Security configuration
security:
  rate_limit_per_min: 5 

# Note: Normalization Methods Applied:
# - name:FIRST        - Standardize name fields (lowercase, remove punctuation, normalize spaces)
# - name:LAST         - Apply to any name field in your data
# - date:DATE_OF_BIRTH - Standardize dates to YYYY-MM-DD format
# - zip:ZIP           - Extract first 5 digits from ZIP codes
# - gender:GENDER     - Standardize gender to single characters (m/f/nb/o/u)
#
# Benefits:
# - "Mary-Jane O'Connor" and "MARYJANE OCONNOR" will match after name normalization
# - "12/25/2023" and "2023-12-25" will match after date normalization  
# - "12345-6789" and "12345 6789" will match after ZIP normalization 