database:
  type: "postgres"
  host: "localhost"
  port: 5432
  user: "cohort_user"
  password: "your_password_here"
  dbname: "cohort_database"
  table: "users"
  fields:
    - "id"
    - "first_name"
    - "last_name"
    - "email"
    - "date_of_birth"

peer:
  host: "localhost"
  port: 8081

security:
  allowed_ips:
    - "127.0.0.1"
    - "::1"
  require_ip_check: true
  max_connections: 10
  rate_limit_per_min: 5

timeouts:
  connection_timeout: 30s
  read_timeout: 60s
  write_timeout: 60s
  idle_timeout: 300s
  handshake_timeout: 30s

logging:
  level: "info"
  file: ""
  max_size: 100
  max_backups: 3
  max_age: 30
  enable_syslog: false
  enable_audit: true
  audit_file: "logs/audit.log"

listen_port: 8080
private_key: "path/to/private.key"
public_key: "path/to/public.key" 