# Example configuration for secure PPRL with cryptographic protocols
# This configuration enables secure comparison functions for private intersection

# Database configuration
database:
  type: csv                           # Currently only CSV is supported
  filename: data/patients_a.csv       # Path to your dataset
  fields: ["first_name", "last_name", "dob", "ssn"]  # Fields to use for matching
  random_bits_percent: 0.01          # Add 1% noise to bloom filters for privacy
  is_tokenized: false                # Set to true if data is already tokenized
  is_encrypted: false                # Set to true if tokenized data is encrypted

# Matching configuration with secure protocols
matching:
  hamming_threshold: 15              # Maximum Hamming distance for matches (stricter for secure mode)
  jaccard_threshold: 0.8             # Minimum Jaccard similarity (higher for secure mode)
  use_secure_protocol: true          # ENABLE SECURE COMPARISON PROTOCOLS

# Peer connection settings
peer:
  host: localhost                    # IP address of peer
  port: 8081                        # Port where peer is listening

# Security configuration
security:
  allowed_ips: ["127.0.0.1", "::1", "192.168.1.0/24"]  # Allowed IP addresses/subnets
  require_ip_check: true             # Enforce IP whitelist
  max_connections: 5                 # Maximum concurrent connections
  rate_limit_per_min: 10            # Connection attempts per minute per IP

# Network timeouts
timeouts:
  connection_timeout: 30s            # Connection establishment timeout
  read_timeout: 120s                 # Read timeout (longer for secure protocols)
  write_timeout: 120s                # Write timeout (longer for secure protocols)
  idle_timeout: 300s                 # Connection idle timeout
  handshake_timeout: 60s             # Protocol handshake timeout (longer for secure)

# Logging configuration
logging:
  level: info                        # Log level: debug, info, warn, error
  file: logs/secure_pprl.log         # Log file path
  max_size: 100                      # Maximum log file size in MB
  max_backups: 3                     # Number of old log files to keep
  max_age: 30                        # Maximum age of log files in days
  enable_audit: true                 # Enable security audit logging
  audit_file: logs/secure_audit.log  # Audit log file path

# Network settings
listen_port: 8082                    # Port to listen on for incoming connections

# Cryptographic keys (will be auto-generated if not provided)
private_key: ""                      # Leave empty for auto-generation
public_key: ""                       # Will be derived from private key 