# Example configuration for Party A in two-party matching
# This demonstrates how to configure the system for multi-party record linkage

database:
  type: csv
  filename: data/hospital_a_patients.csv
  fields:
    - FIRST       # First name field in your dataset
    - LAST        # Last name field in your dataset  
    - BIRTHDATE   # Birth date field (YYYY-MM-DD)
    - ZIP         # ZIP code field

# Party A acts as the receiver in this example
peer:
  host: 127.0.0.1   # IP of Party B
  port: 8082        # Port where Party B is listening

listen_port: 8081   # Port for Party A to listen on

# Unique private key for Party A
private_key: a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456

# Matching configuration optimized for healthcare data
matching:
  bloom_size: 2048           # Larger filter for better accuracy
  bloom_hashes: 8            # More hashes for lower false positive rate
  minhash_size: 256          # Larger signature for better similarity estimation
  qgram_length: 3            # Trigrams for better name matching
  hamming_threshold: 200     # Adjusted for larger Bloom filter
  jaccard_threshold: 0.75    # Higher threshold for healthcare precision
  qgram_threshold: 0.85      # High string similarity requirement
  noise_level: 0.02          # Small amount of privacy noise 