database:
  type: csv
  is_tokenized: true
  tokenized_file: out/tokens_party_a.json  # Path to tokenized data
  # These fields are not used when is_tokenized is true:
  # filename: data/patients_a.csv
  # fields: ["first_name", "last_name", "date_of_birth", "ssn"]
  random_bits_percent: 0.0

peer:
  host: localhost
  port: 8081

security:
  allowed_ips: ["127.0.0.1", "::1", "192.168.1.0/24"]
  require_ip_check: true
  max_connections: 5
  rate_limit_per_min: 3

timeouts:
  connection_timeout: 30s
  read_timeout: 60s
  write_timeout: 60s
  idle_timeout: 300s
  handshake_timeout: 30s

logging:
  level: info
  file: logs/cohort_bridge.log
  max_size: 100
  max_backups: 3
  max_age: 30
  enable_audit: true
  audit_file: logs/audit.log

listen_port: 8080 